stages:
  - build

build-and-run:
  stage: build
  image: docker:20.10  
  services:
    - docker:dind  
  # before_script:
  #   - apk add --no-cache curl nodejs npm  
  #   - npm install -g yarn
  #   - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #   - chmod +x /usr/local/bin/docker-compose
  script:
    - docker-compose -f kafka.yml up -d
    - sleep 20
    - cd service2
    - yarn install
    - yarn start:dev &
    - cd ..
    - sleep 30
    - cd service1
    - yarn install
    - yarn start:dev &
    - cd ..
    - sleep 30
    - cd client
    - yarn install
    - yarn start:dev &
    - sleep 30